version: '3.7'

services:

  web:
    build: .
    container_name: jannonce_web
    command: gunicorn jannonce.wsgi:application --bind 0.0.0.0:8000
    # command: pwd && bash ./entrypoint.sh
    volumes:
      - ./app:/app/jannonce
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: jannonce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=jannoncedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grutil001

  nginx:
    build: ./nginx
    container_name: jannonce_nginx
    volumes:
      - staticfiles:/jannonce/static/
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
