# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='entreprise',
            field=models.CharField(default='', max_length=100, verbose_name='Entreprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 8, 14, 16, 13, 44941), verbose_name='Publi\xe9e'),
        ),
    ]
