# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0003_auto_20161008_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 17, 23, 7, 622138), verbose_name='Publi\xe9e'),
        ),
    ]
