# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0005_auto_20161009_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 17, 25, 41, 523312), verbose_name='Publi\xe9e'),
        ),
    ]
