# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wejob', '0007_auto_20161009_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 21, 23, 12, 801461), verbose_name='Publi\xe9e'),
        ),
    ]
