# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0008_auto_20161009_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 21, 23, 52, 539352), verbose_name='Publi\xe9e'),
        ),
    ]
