# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wejob', '0010_auto_20161010_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 7, 1, 31, 425867), verbose_name='Publi\xe9e'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='piece',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wejob.Categorie'),
            preserve_default=False,
        ),
    ]
