# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0011_auto_20161012_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 7, 15, 20, 3990), verbose_name='Publi\xe9e'),
        ),
    ]
