# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0012_auto_20161012_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 9, 48, 31, 692044), verbose_name='Publi\xe9e'),
        ),
    ]
