# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0013_auto_20161012_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='completed',
            new_name='close',
        ),
        migrations.AddField(
            model_name='tache',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 10, 12, 14, 13, 28, 411000, tzinfo=utc), verbose_name='Date de creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tache',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 10, 12, 16, 13, 1, 745169), verbose_name='Publi\xe9e'),
        ),
    ]
