# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0014_auto_20161012_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='connaisannces',
            new_name='an_connaisannces',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='created',
            new_name='an_created',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='description',
            new_name='an_description',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='divers',
            new_name='an_divers',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='entreprise',
            new_name='an_entreprise',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='formation',
            new_name='an_formation',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='is_active',
            new_name='an_is_active',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='lieu',
            new_name='an_lieu',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='modified',
            new_name='an_modified',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='reponse_employeur',
            new_name='an_reponse_employeur',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='salaire',
            new_name='an_salaire',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='slug',
            new_name='an_slug',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='tags',
            new_name='an_tags',
        ),
        migrations.RenameField(
            model_name='annonce',
            old_name='titre',
            new_name='an_titre',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='created',
            new_name='ta_created',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='description',
            new_name='ta_description',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='modified',
            new_name='ta_modified',
        ),
        migrations.RenameField(
            model_name='tache',
            old_name='titre',
            new_name='ta_titre',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='published',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='close',
        ),
        migrations.AddField(
            model_name='annonce',
            name='an_published',
            field=models.DateField(default=datetime.datetime(2016, 10, 13, 12, 28, 34, 804653), verbose_name='Publi\xe9e'),
        ),
        migrations.AddField(
            model_name='tache',
            name='ta_close',
            field=models.BooleanField(default=False, verbose_name='Clotur\xe9'),
        ),
    ]
