# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejob', '0015_auto_20161013_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='piece',
            new_name='fichier',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='an_published',
            field=models.DateField(default=datetime.datetime(2016, 10, 13, 19, 15, 19, 338098), verbose_name='Publi\xe9e'),
        ),
    ]
